services:
  amichiamoci:
    build: ./
    ports:
      - 80:80
    networks:
      - db
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=amichiamoci
      - MYSQL_HOST=mysql
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=changeme
      # - SITE_NAME=Amichiamoci
      # - DOMAIN=localhost
      # - ADMIN_PATH=/
      # - CF_TURNSTILE_TOKEN=
    volumes:
      - ./uploads:/uploads:rw
    depends_on:
      mysql:
        condition: service_started
  
  mysql:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=amichiamoci
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    networks:
      - db
    ports:
      - 8080:80
    restart: always

networks:
  db: 
    driver: bridge
  