<?php include "./load/config.php"; ?>
<span>CURRENT_PROTOCOL: "<?= CURRENT_PROTOCOL ?>"</span><br>
<span>DOMAIN_URL: "<?= DOMAIN_URL ?>"</span><br>
<span>ADMIN_PATH: "<?= ADMIN_PATH ?>"</span><br>
<span>ADMIN_URL: "<?= ADMIN_URL ?>"</span><br>
<span>UPLOAD_PATH: "<?= UPLOAD_PATH ?>"</span><br>
<span>SERVER_UPLOAD_PATH: "<?= SERVER_UPLOAD_PATH ?>"</span><br>
<span>EMAIL_SOURCE: "<?= EMAIL_SOURCE ?>"</span><br>
<span>CONTACT_EMAIL: "<?= CONTACT_EMAIL ?>"</span><br>
<span>$_SERVER["DOCUMENT_ROOT"]: "<?= $_SERVER["DOCUMENT_ROOT"] ?>"</span><br>