name: Docker image build and push

on:
  push: 
    branches: ['main']

env:
  APP_NAME: staff
  DOCKER_USERNAME: amichiamoci

jobs:
  docker:
    name: Build and publish image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Change repository owner to lowercase
        id: repo_owner
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository_owner }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repo_owner.outputs.lowercase }}/${{ env.APP_NAME }}
          labels: |
            org.opencontainers.image.title=Amichiamoci Staff
            org.opencontainers.image.description=Portale Staff per Amichiamoci
            org.opencontainers.image.vendor=Amichiamoci

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.DOCKER_USERNAME }}/${{ env.APP_NAME }}:latest
            ghcr.io/${{ steps.repo_owner.outputs.lowercase }}/${{ env.APP_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}